### ISSUE TITLE
Masking of * Star not working in syntax highlighting.

### ISSUE THREAD

**Issue by janArb** [asciidoctor/asciidoctor-intellij-plugin#1017]
Hey,

I was confused by the syntax highlighting if using the * Star in inline code. 
The syntax highlighting prints the text between two of such inline code in bold, indicating the formatting from the * Star outside of inline code in pure text blocks:

Example 1:
This is a text block using a `*` with inline code formatting two times `*`.

Now all the text between the two stars is bold, although the formatting shouldn't apply.
Even masking the Star with two dollar signs doesn't help:

Example 2:
This is a text block using a `$$*$$` with inline code formatting two times `$$*$$`.

**Comment by Grolribasi** [comment]
AsciiDoc syntax says that text between two stars should be bold. This is the intended behsvior. If you don't want a star to be recognized as syntax element, you can sescape it like this: `\*`. Or use HTML substitution.

**Comment by ahus1** [comment]
Hi @janArb - thanks for reporting this. The AsciiDoc plugin (this project) tries to give a good estimation as it will be rendered by the Asciidoctor implementation in the preview. 

When I enter the following in the editor:

```
This is a text block using a `*` with inline code formatting two times `*`.
```

this shows like this in the editor

![image](https://user-images.githubusercontent.com/3957921/160482403-8a72c180-b223-4ad6-b6e1-c68c2352a4e7.png)

and in the preview

![image](https://user-images.githubusercontent.com/3957921/160482467-93e3dbd3-c25d-4217-8fec-6005fe5d7658.png)

so I think these two are quite close, and this is fine. 

When using the dollar signs like this

```
This is a text block using a `$$*$$` with inline code formatting two times `$$*$$`.
```

the editor shows 

![image](https://user-images.githubusercontent.com/3957921/160482711-1068815d-26d2-4e33-b1d5-d56faad2ff7b.png)

while the preview shows

![image](https://user-images.githubusercontent.com/3957921/160482779-ddf5e41c-dffe-4fed-ba63-fb89b3dac2c5.png)

This is indeed unexpected, and it should be fixed in the AsciiDoc plugin for IntelliJ, as it doesn't understand the syntax of `$$` to escape content.

As @Grolribasi mentioned, you can use a backslash. Another way to escape a block of text is one or more plug signs, see https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/#single-double-plus for details.

I'll see how I can support the escaping with `$$` as this syntax is documented for AsciiDoc.py. Apparently it is supported for Asciidoctor, but not documented as Asciidoctor seems to favor the plus signs instead.

**Comment by ahus1** [comment]
The `$$` syntax will be supported by the next release of the plugin. I'll update this issue once a pre-release is available. 

With that pre-release, the wrapping/unwrapping of selected text with `+` and `$` is supported: To wrap some text, select it, and then type either `+` or `$`. If the text is already wrapped, the character will unwrap it.

**Comment by mojavelinux** [comment]
> I'll see how I can support the escaping with $$ as this syntax is documented for AsciiDoc.py. Apparently it is supported for Asciidoctor, but not documented as Asciidoctor seems to favor the plus signs instead.

This is a deprecated feature of the AsciiDoc syntax and will likely be removed by the spec. Please don't rely on it, if possible. It should be a warning if used.

**Comment by ahus1** [comment]
Thanks @mojavelinux for pointing this out. I looked into the docs and didn't find it, and wasn't sure if this is obsolete. 

The next version will have an inspection that will show a warning if this is used, and will provide a quick-fix to rewrite it as passthrough with a plus (+) or as an inline pass macro.

**Comment by ahus1** [comment]
Pre-release 0.37.18 is now available that includes this fix.
