### ISSUE TITLE
Exceptions after the update

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1048]
## Observed vs. expected behavior

After updating to AsciiDoc 0.37.18 exceptions keep on occuring.

Exceptions just happen in random places.

I am attaching the exception stacktrace:

[induced1.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8569980/induced1.txt)
[exception.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8569981/exception.txt)
[exception2.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8569982/exception2.txt)

## Environment

Plugin Version:  AsciiDoc 0.37.18 

IntelliJ Details:
IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.18)

Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by Grolribasi** [comment]
Seems like internal bug that is not reproducing after the IDE retart.

**Comment by ahus1** [comment]
Thanks for sharing these logs ... it seems that the old version of the plugin wasn't completely unloaded. Strange, normally the IDE should ask for a restart after the new version was installed, and the old version should still run. 

Can you please post the steps you took to install the plugin update? Maybe you could even share your IDE's log via Email (you'll find my email address on my GitHub profile). Maybe something went wrong during installation. 

You'll find the log via "Help | Show log in Explorer". Sometimes it contains personal information, that's why you usually want to review it, and not post it on a public issue like that.

**Comment by ahus1** [comment]
Thank for your recollection of the events, this helps a lot. 

Please enjoy your vacation and stay safe! Let's have a look at the logs once you're back.

**Comment by ahus1** [comment]
I reviewed the logs and could unfortunately not find an immediate cause.
