### ISSUE TITLE
“Enable Formatting” parameter turning back on by itself after IDE update?

### ISSUE THREAD

**Issue by mminot-yseop** [asciidoctor/asciidoctor-intellij-plugin#1099]
## Observed vs. expected behavior

I noticed several times that the “Enable Formatting” parameter (Editor → Code Style → AsciiDoc), [which I always turn off](https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/428#issuecomment-1183144214), turned back on without any specific action on my part. My guess is that it happens during major IntelliJ updates, but I can’t be sure. Could be some plugin updates as well. Or a mixture of the two, since I noticed that my latest IDE update triggered a major update of the plugin, whose initially installed version was not compatible with the new IDE version.

Expected behavior: Settings such as this one should be preserved through time, regardless of IDE updates or plugin updates.

## Steps to reproduce

I suppose it’d go like…

* Use IntelliJ 2021.2.3 with its favored compatible version of the AsciiDoc plugin.
* Set “Enable Formatting” to false.
* Update IntelliJ to 2022.1.3 (I did so using the JetBrains Toolbox).
* Update the AsciiDoc plugin, which should be yelling about not being compatible with the new IDE version.
* See “Enable Formatting”.

… but there may be other factors that I failed to identify.

## Environment

Plugin Version: 0.37.27

IntelliJ Details:

```
IntelliJ IDEA 2022.1.3 (Ultimate Edition)
Build #IU-221.5921.22, built on June 21, 2022
Licensed to XXXXX
Subscription is active until XXXXX.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-52-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1126M
Cores: 8
Non-Bundled Plugins:
    com.dubreuia (2.3.0)
    org.asciidoctor.intellij.asciidoc (0.37.27)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    com.haulmont.jpab (2022.3.0-221)
    Pythonid (221.5921.27)

Kotlin: 221-1.7.0-release-281-IJ5591.52
Current Desktop: XFCE
```

**Comment by ahus1** [comment]
Thanks for reporting this. The AsciiDoc plugin builds on top of the IntelliJ functionalities. When you see this happening with the AsciiDoc code formatting settings, I assume you'll see the same behavior with other formatting settings. 

I suspect that this happens when settings are saved as IDE settings and then the toolbox application creates a new folder for a new IDE version (2022.1 -> 2022.2). I suggest you create an issue against the toolbox app: https://youtrack.jetbrains.com/issues/TBX. Please post the issue's link here, so people can follow up on that issue. 

One way to preserve your settings would be to use project specific settings (that has it pros and cons, of course). One of the pro things about project specific configurations is that they can be committed to the code repository and are then active for all collaborators on the project.

Project specific settings can be stored in the JetBrains's XML format in `.idea/codeStyles/...`, or in the `.editorconfig` file. Auto-completion works in the `.editorconfig` file, and the option you'd be looking for would be `ij_asciidoc_formatting_enabled = false`.

Please let me know if this information is helpful to you.

**Comment by mminot-yseop** [comment]
Thanks for that answer.

> Thanks for reporting this. The AsciiDoc plugin builds on top of the IntelliJ functionalities. When you see this happening with the AsciiDoc code formatting settings, I assume you'll see the same behavior with other formatting settings.

Hum I did not notice much change, but we mostly use the “Adapter for Eclipse Code Formatter”, which uses project-specific settings, so that may shield it from the issue.

> I suspect that this happens when settings are saved as IDE settings and then the toolbox application creates a new folder for a new IDE version (2022.1 -> 2022.2). I suggest you create an issue against the toolbox app: https://youtrack.jetbrains.com/issues/TBX. Please post the issue's link here, so people can follow up on that issue.

Here you go: https://youtrack.jetbrains.com/issue/TBX-8000/Lost-plugin-preferences-after-IntelliJ-IDEA-Ultimate-updates

> One way to preserve your settings would be to use project specific settings (that has it pros and cons, of course). One of the pro things about project specific configurations is that they can be committed to the code repository and are then active for all collaborators on the project.
> 
> Project specific settings can be stored in the JetBrains's XML format in `.idea/codeStyles/...`, or in the `.editorconfig` file. Auto-completion works in the `.editorconfig` file, and the option you'd be looking for would be `ij_asciidoc_formatting_enabled = false`.

Sounds nice; will try that on one or two projects to see how it goes, thank you.

**Comment by ahus1** [comment]
Thanks for sharing the number of the issue you created in YouTrack. I added my vote to it.

With the contents from this issue, there is now a new page about reformatting the plugin's user guide: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/reformatting.html

I'm closing this issue as there seems nothing else I can do within the scope of the plugin. Please comment if you think otherwise, and I'll re-open the issue.
