### ISSUE TITLE
Cannot change the colour scheme for inline macros.

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#1105]
## Observed vs. expected behavior

If you try and the colour associated with inline macros, it doesn't seem to work. It always seems to select the block macro setting while trying to change it.

## Steps to reproduce

1. Go into IDEA settings
2. Select Editor -> Color Scheme -> Asciidoc
3. Now try this:

https://user-images.githubusercontent.com/77050471/179713142-3d0fee8c-03c4-418a-8614-7fe929ace631.mov

## Environment

Plugin Version: 0.37.32

IntelliJ Details: ____

IntelliJ IDEA 2022.2 Beta (Ultimate Edition)
Build #IU-222.3345.47, built on July 14, 2022

Expiration date: August 13, 2022
Runtime version: 17.0.3+7-b469.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    kotlin.code-vision.usages=true
    kotlin.code-vision.inheritors=true

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (222.3345.16)
    com.nasller.CodeGlancePro (1.4.5)
    com.mroche.JsonHelper (1.2.0)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.plugins.watcher (222.3345.16)
    com.intellij.plugins.expui (0.4)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.guice (222.3345.16)
    String Manipulation (9.5.0)
    Shifter (1.9.6)
    PlantUML integration (5.15.2)
    org.jetbrains.plugins.ruby (222.3345.47)
    org.jetbrains.plugins.vue (222.3345.40)
    com.intellij.plugins.webcomponents (222.3345.16)
    com.intellij.plugins.html.instantEditing (222.3345.16)
    com.dmarcotte.handlebars (222.3345.16)
    org.asciidoctor.intellij.asciidoc (0.37.32)
    com.github.beansoft.iscratch (2022.2.4)
    Pythonid (222.3345.47)
    DBN (3.3.1923.0)
    com.thoughtworks.gauge (222.3345.16)
    izhangzhihao.rainbow.brackets (6.25)
    Batch Scripts Support (1.0.13)

Kotlin: 222-1.7.10-release-334-IJ3345.47

**Comment by RayOffiah** [comment]
I think I've fixed it.

https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/1116

**Comment by ahus1** [comment]
This change is now available as part of pre-release 0.37.35. I'll wait for some days for this and other changes to "burn in", and will then publish it as a regular release. If you'd like to have an earlier release due to, for example, the workflow in your team, please let me know. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
