### ISSUE TITLE
Should support Hugo

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-intellij-plugin#1128]
Hugo is one of the most popular open-source static site generators, it should be supported.

I write the post in WebStorm, but the images can not find the directory.

**Comment by ahus1** [comment]
Thanks for raising this request. In order to support a specific directory layout there should be some marker that (like a `pom.xml` marks a Maven project, or a `antora.yml` that marks an Antora component). 

I assume you refer to a project like https://github.com/diguage/www.diguage.com. I'm not familiar with Hugo, and I don't see a marker file there. 

As an alternative, there is a generic mechanism in the plugin to provide hints about images to the AsciiDoc plugin: the `.asciidoctorconfig` file: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

Usually this is solved by adding an `imagesdir` to the `.asciidoctorconfig` file if the images are relative. Looking at the repository above, those targets start with `/`, thereby they are absolute. 

One way to solve that could have been introducing an attribute plus an `ifdef::env-idea[]` as described here https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/conditional-rendering.html possibly in each blog post. 

As an alternative I updated the image resolving for the preview in the plugin; it now uses the `imagesdir` for the preview even when image targets start with a `/`. 

To try this out, install the latest pre-release 0.37.40 of the AsciiDoc plugin. Then add a file like the following in the root of the project: 

```
// .asciidoctorconfig in the root of the project
:imagesdir: {asciidoctorconfigdir}/static
```

This will then show as follows in the editor and in the preview. You'll also notice that auto-completion works for the images in the editor. 

![image](https://user-images.githubusercontent.com/3957921/184008692-34e27a83-ebdf-429d-a20e-bbab4ab5f3be.png)

Please give it a try and let me know how this works for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by diguage** [comment]
I tested the config file:

```
// .asciidoctorconfig in the root of the project
:imagesdir: {asciidoctorconfigdir}/static
```

It did not work well for me.

![image](https://user-images.githubusercontent.com/2121467/184057521-90ffb417-7339-4897-a05e-64abc53c44cc.png)

```
WebStorm 2022.2
Build #WS-222.3345.108, built on July 23, 2022
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    PlantUML integration (5.16.1)
    org.asciidoctor.intellij.asciidoc (0.37.36)
```

**Comment by ahus1** [comment]
As described above, please update to pre-release 0.37.40 first. It will not work with earlier releases.

**Comment by diguage** [comment]
Hugo does not have marker.

```bash
# Clone the hugo site
$ git clone git@github.com:diguage/www.diguage.com.git

# clone the theme
$ git submodule update --init --recursive

# Set up the hugo
$ hugo server
# Then you can access the site throuth: http://localhost:1313/

### another way

# Build the site in product model
$ hugo --minify
# Then the build site in the public folder,
$ cd public
$ python -m http.server 8000 # Python3
# Then you can access the site throuth: http://localhost:8000/
```

The config file of Hugo is in `config` folder,  `config/_default` is used in `hugo server` and `config/production` is used in `hugo --minify`。

```bash
╭─☞ /path/to/www.diguage.com git:(master)
╰─➜ $ tree
.
├── LICENSE
├── README.adoc
├── archetypes
│   └── default.adoc
├── config              $ Config folder
│   ├── _default
│   │   └── config.toml $ Be used in `hugo server`
│   └── production
│       └── config.toml $ Be used in `hugo --minify`
├── content 
│   ├── about.adoc
│   ├── archives.adoc
│   └── post            $ the articles
│       └── asciidoc-vs-markdown.adoc
├── resources
│   └── _gen
│       ├── assets
│       └── images
├── static
│   ├── ads.txt
│   ├── css
│   │   ├── asciidoctor.css
│   │   ├── rouge-github.css
│   │   └── rouge-monokai.css
│   └── images          $ images folder, be used as `image::/images/website/hugo-logo.svg[]`
│       ├── avatar.jpg
│       ├── website
│       │   ├── asciidoc.png
│       │   ├── hugo-logo.svg
│       │   ├── markdown.png
│       │   └── wordpress.png
│       └── wireframes
│           └── best-architecture.png
└── themes
    └── mainroad        $ the theme folder
```

@ahus1  Maybe it helps you.

**Comment by diguage** [comment]
> As described above, please update to pre-release 0.37.40 first. It will not work with earlier releases.

OK. Let me try it.

**Comment by ahus1** [comment]
Thanks for trying this.

I'd be happy to add some automatic rules for Hugo, and for that I would need to know more about Hugo:

- the config folder can also be a config.toml file AFAIK
- will the folder static have always the same name independent of the theme or config being used?

I don't need a single marker file, it could also be more complex rules - they only need to be specific and reliable. Can you please help me here? Thanks!

**Comment by diguage** [comment]
It's my pleasure.

1. The config folder is fixed, and the config file is one of `config.toml`, `config.yaml` or `config.json`.
2. The folders are always the same regardless of theme.

**Comment by ahus1** [comment]
There is now pre-release 0.37.41 that automatically detects Hugo. The docs describe how the detection works, and how images in `static` can be referenced: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/hugo.html - it also mentions how page resources work, so that they are closer to the blog post and not in the `/static` folder.

The `.asciidoctorconfig` file is no longer necessary for the images. Still, it can help you to use the same CSS from the site for the preview; see the link at the end of the Hugo documentation page for details. 

Please install the preview and let me know how this works for you. Support for other Hugo features might be added over time. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by diguage** [comment]
I tested the plugin, it is OK.

I read the https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/hugo.html , there is an error.

```
// show a global resource with an absolute target
image::/static/images/image-in-static.png[]  # the path is wrong.
↓
image::/images/image-in-static.png[]  # the path is right.
```

**Comment by ahus1** [comment]
Thanks for taking the time to test and review it. I fixed the docs. 

Closing this issue. If you find any other feature that is missing for Hugo, please open another issue.
