### ISSUE TITLE
JavaFX preview doesn't support darcula theme (0.14)

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#122]
This is not implemented yet. 

The JavaFX preview uses  different set of CSS files. A new CSS darcula theme needs to be created from the original Asciidoctor CSS theme.

**Comment by ahus1** [comment]
The JavaFX preview uses the Asciidoctor's original CSS theme. 

@bodiam @mojavelinux - is the an official "dark" Asciidoctor CSS theme?

**Comment by bodiam** [comment]
Hmm, I think it will take ages for that to happen, if ever. Wouldn't a fix to just use a semi black background and white font be a simple solution?

**Comment by mojavelinux** [comment]
> @bodiam @mojavelinux - is the an official "dark" Asciidoctor CSS theme?

Not yet. However, one could be created. You could also consider using https://github.com/darshandsoni/asciidoctor-skins which includes a dark theme.

> Wouldn't a fix to just use a semi black background and white font be a simple solution?

Themes are more complicated than that due to the fact that AsciiDoc has such a rich set of components. I think a partial solution will only lead to a lot of issue reports. We should do it right or not at all.

...honestly, it doesn't take that long to make a new stylesheet ;)

**Comment by ahus1** [comment]
This will be part of 0.16.1 to be released later today.
