### ISSUE TITLE
Change to Gradle build

### ISSUE THREAD

**Issue by yole** [asciidoctor/asciidoctor-intellij-plugin#126]
The development experience can be improved by changing the build of the plugin to use Gradle and the [Gradle IntelliJ plugin](https://github.com/JetBrains/gradle-intellij-plugin).

(Filing this as an issue to get feedback first. If there are no objections, I'll implement this myself.)

**Comment by ahus1** [comment]
Using a proper Gradle IntelliJ plugin sounds promising - especially the tasks like buildPlugin and runIdea as listed on its README.md. (There's been a previous attempt to move to a Gradle using a vanilla Gradle setup. That turned out to be fragile.)

+1 from me. I'd be happy to receive a pull request. Let me know if you want to shuffle source folders. 

@bodiam - what do you think?

**Comment by mojavelinux** [comment]
@ancho, this might interest you. You did such a wonderful job with the Gradle build for AsciidoctorJ.

**Comment by bodiam** [comment]
I'm very okay with this. The only reason why we revered it was that Intellij didn't like the Gradle build at all. 

If that's fixed, I see no reason not to use Gradle.

**Comment by ancho** [comment]
Nice. Just let me know if you need any help.

**Comment by gengjiawen** [comment]
I have create a pr for this :)

**Comment by ahus1** [comment]
PR is merged, thanks @gengjiawen!
