### ISSUE TITLE
Hard unset attributes does not work in Preview

### ISSUE THREAD

**Issue by LukeCz** [asciidoctor/asciidoctor-intellij-plugin#1278]
## Observed vs. expected behavior

Hello, The plugin understands attributes defined in antora.yml in the preview however the hard unset (https://docs.antora.org/antora/latest/component-attributes/#hard-unset) does not work - the preview allows to redefine the attribute while the actual Antora build correctly does not.

## Steps to reproduce

Define in antora.yaml:

```
asciidoc:
  attributes:
    abc: ~
```

Create temp.adoc:

```
:abc: 111

{abc}
```

The result in preview should be blank and not "111".

## Environment

Plugin Version: 0.38.4

IntelliJ IDEA 2022.3.1 (Community Edition)
Build #IC-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2006M
Cores: 20
Non-Bundled Plugins:
    idea.plugin.protoeditor (223.8214.6)
    com.intellij.grazie.pro (0.3.200-223)
    org.asciidoctor.intellij.asciidoc (0.38.4)

Kotlin: 223-1.7.21-release-272-IJ8214.52

**Comment by ahus1** [comment]
Thanks for reporting this and sorry this causes you troubles. I confirm that this is a bug. Expect a fix in the next upcoming release.

**Comment by ahus1** [comment]
There is now pre-release 0.38.8 which contains a fix. Please give it a try.

One thing I noted: instead of a blank line, the preview will now show `{abc}` as the attribute is not defined. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
Closing the issue as it works for me when I tested it. If you experience issue, please comment here and I'll re-open the issue.
