### ISSUE TITLE
Wrong nesting of ordered and unordered lists

### ISSUE THREAD

**Issue by oleksiidn** [asciidoctor/asciidoctor-intellij-plugin#1346]
## Observed vs. expected behavior
[Navigation in the structure tool window](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/technical-writing/navigating-in-a-project.html#navigation-in-the-structure-tool-window) doesn't nest ordered and unordered lists correctly. 

## Environment

Plugin Version: 0.38.13

 
 
![image](https://user-images.githubusercontent.com/98417392/235153704-d86ddada-4187-4b0b-ac92-7a4c5cd4a988.png)

**Comment by ahus1** [comment]
Thank you for reporting this. This indeed looks like a bug. I'll have a look.

**Comment by ahus1** [comment]
I've been able to reproduce the problem and developed a fix. The fix will be available in the next release. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
I pushed another change to fix a regression introduced by the first change. Once this GitHub action is complete, I'll prepare a pre-release.

**Comment by ahus1** [comment]
There is now pre-release 0.38.14 which includes the change and also the fix for the regression. Please give it a try if this change and the other included into the release work for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by oleksiidn** [comment]
It works well. Thank you!

**Comment by ahus1** [comment]
Thanks again for reporting and testing this. I plan to publish the next regular release in about a week.
