### ISSUE TITLE
Preview of images with Antora

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor-intellij-plugin#1366]
## Observed vs. expected behavior

Expected `image:./image.png[]` and `image::./image.png[]` to both display image.png in the preview. Instead:

- The inline image macro `image:./image.png[]` previewed the image.
- The block image macro `image::./image.png[]` did not.

## Steps to reproduce

Create an Antora component with mirrored paths under both images and pages family folders.

**Files**
```
antora.yml
modules/doc/nav.adoc
modules/doc/pages/2023/05/24/feature-x/index.adoc
modules/doc/images/2023/05/24/feature-x/image.png
```

**Test file index.adoc**
```asciidoc
= Test relative paths

images:./image.png[]

images::./image.png[]

```

## Environment

Windows 10 lastest.

Plugin Version: 0.38.17

PyCharm 2022.2.3 (Community Edition)
Build #PC-222.4345.23, built on October 10, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    com.samdark.intellij-visual-studio-code-dark-plus (2.7)
    com.markskelton.one-dark-theme (5.7.4)
    com.jetbrains.darkPurpleTheme (1.3)
    com.github.dinbtechit.vscodetheme (1.8.0)
    com.fernandojimenez.mattecarbon.theme (3.0.0)
    org.asciidoctor.intellij.asciidoc (0.38.17)

IntelliJ Details: PyCharm Community Edition

Thankyou for an awesome plugin.

Best regards, Sturt

**Comment by ahus1** [comment]
Thanks for reporting this and sorry this caused you troubles. 

With the test case you provided, I was able to create a test case and fix the issue. It will be available in the next release of the plugin. I'll update this issue once a pre-release is available.

**Comment by sturtison** [comment]
> Thanks for reporting this and sorry this caused you troubles.
> 
> With the test case you provided, I was able to create a test case and fix the issue. It will be available in the next release of the plugin. I'll update this issue once a pre-release is available.

Thank you for looking at the matter and for developing such a good plugin.

**Comment by ahus1** [comment]
The pre-release 0.38.18 is now available which fixes this bug. Please give it a try if it works for you as expected.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by abonne01-pro** [comment]
Hello,
I'm having a similar issue. 
Observed vs. expected behavior
`image::` is not recognized in syntax view and in preview:

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/154422018/0789c4af-0bdc-4eab-92d6-14a7b3e823ac)

`image:` is working
![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/154422018/e9be5ad9-a908-4378-8f3c-9e134471fd79)

how to reproduce : 
```
Root\
|- images
    |-trigger-fired.png
    |-trigger-actions.png
|- pages
  |- mypage.adoc
```
header of mypage.adoc 
:imagesdir: ../images/

preview only works for image: and not image::


thanks for correction.

Env info 

PhpStorm 2023.3.1
Build #PS-233.11799.297, built on December 11, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
  org.asciidoctor.intellij.asciidoc (0.41.2)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
