### ISSUE TITLE
Support RustRover

### ISSUE THREAD

**Issue by sdavids** [asciidoctor/asciidoctor-intellij-plugin#1456]
## Why the new feature should be added

It is supported in all the other JetBrains IDEs so far.

## How the new feature should work

One can install the IntelliJ AsciiDoc Plugin from the JetBrains Marketplace into [RustRover](https://www.jetbrains.com/rust/).

<img width="547" alt="rustrover" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/201931/eaacd342-94c8-4677-9b06-9661f8b4e074">

**Comment by ahus1** [comment]
Thanks for raising this. I found that the Marketplace didn't allow installations on EAP versions due to the version number range. I'm about to fix this, but the settings seems to be cached. 

Plugin version 0.40.7 should work with the current RustRover EAP 233.8264.32.

For now, please download the plugin's ZIP file manually and install it as described in the user's docs: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation.html#download-install-from-disk.

**Comment by ahus1** [comment]
Update: the cache seems to have been updated, and installation via the marketplace should work as usual. Please give it a try. If it works for you, please close this issue.

**Comment by sdavids** [comment]
verified
