### ISSUE TITLE
Preview: URL does not work for script in docinfo

### ISSUE THREAD

**Issue by LukeCz** [asciidoctor/asciidoctor-intellij-plugin#1508]
## Observed vs. expected behavior

Hello. I'm not sure if this is a known issue. I'm trying to execute JavaScript in docinfo in preview window. The script works when embedded directly in html but does not work when loaded remotely using <script src=...
Is there a way to debug this? In IJ is there a way to look at JS console for errors?

## Steps to reproduce

Attached is a very minimal example. One adoc file loads footer with embedded script while the other one with an URL.
NOTE: in this example, a local webserver with the script.js has to be started prior and the host, port and path in index-docinfo-footer.html may need to be modified.
One file correctly displays TEST in preview while the other one, with the same code just using an URL, does not. Screenshots attached.
When I open the page in Edge (using the Edge icon in IJ), the TEST is displayed correctly, proving the JS file is found and executed.

## Environment

Plugin Version: 0.41.6

IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4006M
Cores: 16
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  com.intellij.grazie.pro (0.3.271)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  org.asciidoctor.intellij.asciidoc (0.41.6)
Kotlin: 233.13135.103-IJ

[test.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/13829139/test.zip) 
![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/6900878/c07afbdf-3ea0-4290-bb74-701007ef3e5e)
![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/6900878/efbfcfff-22db-4d58-92b9-666ea37190e1)

**Comment by ahus1** [comment]
Thanks for reaching out. See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#benefits-of-the-jcef-preview on how to access the developer tools to inspect the HTML and the JavaScript console. 

As you suspected, it is a CSP problem. The current preview uses a `file://` URL and doesn't allow including JavaScript files due to the CSP policy. 

Even if your JavaScript takes this CSP, there is another challenge: The AsciiDoc plugin is making extensive use of replacing the content in-place to avoid a flickering preview. While hooking into those mechanisms might be possible (but is unsupported and break between releases), I'd advise against it as it will probably lead to a brittle user experience. 

I suggest restrict customizing the preview to CSS.

**Comment by LukeCz** [comment]
Thank you for pointing me to the right direction - JS console is a gold mine of information, it clearly shows CSP as the root cause.

I agree with your reasoning to keep the tool safe. I looked at createCSP method and you are already adding highlightjs to the list of exceptions. Maybe there could be another attribute with whitelisted URL added?

What I'm trying to do is customize highlight.js (loaded via :highlightjsdir: URL) by adding some before:highlightElement plugin. But maybe there is a better way?

That all said I fully understand this is not a bug in the current implementation. And thank you again for detail explanation.

**Comment by ahus1** [comment]
Might be related: #1510
