### ISSUE TITLE
callout lists do not behave nicely if it comes to list continuation

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#151]
``` asciidoc
* foo
* bar

1> baz
2> bam

* foo baz
* bar bam

. foo
. bar
+
asdf

foo
```

will render like

![example1](https://cloud.githubusercontent.com/assets/325196/19840554/873fc63e-9ef8-11e6-93b9-c38171be4e67.JPG)

This means that
- another list (`foo / bar`) that should be continued by a callout list (`baz / bam` should be a sublist of `bar`) is not automatically continued like described at http://asciidoc.org/userguide.html#X64, explicit continuation works however
- a callout list that is continued, either implicitly with another list type, a literal paragraph or explicitly with the list continuation sequence (`\n+\n`) is not rendered correctly, but the continuing stuff vanishes

The example should probably render like

![example2](https://cloud.githubusercontent.com/assets/325196/19840644/fcd35814-9efa-11e6-8525-932e8e7267b5.JPG)

And if `foo baz / bar bam` would have two asterisks instead of one, it should probably be a sublist of `bam`.

**Comment by ahus1** [comment]
The plugin is using Asciidoctor (https://github.com/asciidoctor/asciidoctor) to render the preview. It looks to me that it is missing support for some of the nested callout cases. 

Please post an issue there together with examples. Once Asciidoctor can handle it (and the change has propagated to AsciidoctorJ) the IntelliJ plugin will support it as well in an upcoming release.

Thanks!

**Comment by mojavelinux** [comment]
Callout lists are not part of the normal list hierarchy. In other words, they are treated as regular blocks, not given any sort of special treatment as a child of a list. Therefore, if you want a callout list to be the child item of another list, you need to use a list continuation.

```
* foo
* bar
+
1> baz
2> bam

* foo baz
```

It might even be better/safer to put it inside an open block:

```
* foo
* bar
+
--
1> baz
2> bam
--
* foo baz
```

Unlike other lists, a callout list is primitive and is implemented as such. Whatever advanced nesting features it does support are undefined. The reason is that callout lists are intended to be used directly below a verbatim block and not really anywhere else.
