### ISSUE TITLE
line length limit

### ISSUE THREAD

**Issue by zohar-amir-personetics** [asciidoctor/asciidoctor-intellij-plugin#1551]
## Why the new feature should be added

When writing documentation, I usually have the rendered doc open to the right of my editing window. This makes it difficult to track the length of my lines. I would not like my lines to exceed X characters long.

## How the new feature should work

1. Configure a max line length.
2. break lines on word boundaries such that no line exceeds the configured max length (maybe allow a bit of "tolerance").

**Comment by ahus1** [comment]
Thank you for reaching out with this enhancement idea. 

The AsciiDoc community suggests the following around line handling: 
* [One sentence per line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line) - see the link for the reasons for that. The auto-formatting of AsciiDoc content can re-format for one-sentence-per-line (Ctrl+Shift+L), still users can disable this in the plugin's settings.
* For AsciiDoc contents, users then configure their IDE with soft-wraps for lines. I suggest to users to enable this per file type in the IntelliJ settings:    
   ![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/f7b3ce97-159c-4e25-a062-8fcab7aba530)

For those who don't want to see soft-wraps, they can configure the AsciiDoc plugin to use a horizontal split instead of a vertical split, thereby showing longer lines in the editor. 

Having said all that, if you prefer your IDE to wrap your lines in mid-sentence, there is the option "wrap on typing" which might be what you want. The same menu allows you to configure additional visual rules. This setting is available on project and IDE level. The plugin doesn't provide auto-formatting content this way due to the once-sentence-per-line convention linked above.

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/0c10e72b-5a3f-46d2-ad8b-a40e94a5c91b)

Please let me know if this resolves your situation.

**Comment by ahus1** [comment]
I hope my answer provided some insights. Closing this as there were no further questions. Feel free to comment again and I'll re-open the issue.
