### ISSUE TITLE
JavaFX WebView preview headers and table-of-contets fonts are illegible

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoctor-intellij-plugin#186]
When using JavaFX WebView for preview headers and table-of-contets fonts are illegible.

![screen shot 2017-08-18 at 3 07 23 pm](https://user-images.githubusercontent.com/61612/29479768-0479ff46-8429-11e7-80fd-b0315261fdab.png)

AsciiDoc Plugin Version: 0.19.0

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 14, 2017
Licensed to Michael Gilligan
Subscription is active until January 15, 2018
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by ahus1** [comment]
@msgilligan - I haven't see something like this before. I can only guess what the reason could be. 

My first guess would be a font issue: headings and toc use the following font order for JavaFX: "Open Sans","DejaVu Sans",sans-serif with font-weight 300 (="light") - see the default.css in the javafx folder.

It might be that you've installed a OpenSans font as TTF that doesn't support all glyphs. This font is normally used a Google web font and it is distributed as multiple TTFs in Google's style sheets, maybe it was installed on your Mac accidentally. Either remove the font or replace it with a TTF that supports all glyphs (see here: http://www.1001fonts.com/open-sans-font.html) 

If you don't have "Open Sans" installed, it might be a similar problem with the second font "DejaVu Sans". You can download the DejaVu fonts here: https://dejavu-fonts.github.io/

If none of the fonts above is installed, JavaFX will pick a "sans-serif" font. This depends a lot on your local setup. But maybe the result will improve if you start installing the "DejaVu Sans" fonts. 

This answer turns out to be quite technical... please let me know if this was still helpful.

**Comment by ahus1** [comment]
closed due to no feedback.

**Comment by msgilligan** [comment]
Sorry, I just didn't have time to troubleshoot...

**Comment by ahus1** [comment]
... just re-open if you have the time. Thanks!

**Comment by msgilligan** [comment]
I had neither the "Open Sans" or "DejaVu" fonts installed. I installed them and the problem went away.

**Comment by msgilligan** [comment]
Should the requirement that these fonts be installed be documented somewhere? Is this a macOS only issue?

**Comment by ahus1** [comment]
Hi - please see the pro/con discussion as part of #184. Maybe we should include them by default.
