### ISSUE TITLE
Blurred text in JavaFX

### ISSUE THREAD

**Issue by gudaoxuri** [asciidoctor/asciidoctor-intellij-plugin#209]
Swing is normal :

![snipaste_2018-06-02_10-14-57](https://user-images.githubusercontent.com/2802567/40869516-286bd0b0-664f-11e8-8e33-948d1af19939.png)

JavaFX webview like this:

![snipaste_2018-06-02_10-15-15](https://user-images.githubusercontent.com/2802567/40869518-2e90b140-664f-11e8-9dd1-091b7fbbc313.png)

AsciiDoc Plugin Version: 0.20.6 and previous versions

IntelliJ IDEA 2018.1.4 (Ultimate Edition) and previous versions
Build #IU-181.5087.20, built on May 17, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by gudaoxuri** [comment]
I closed HiDPI support in idea.properties

`sun.java2d.uiScale.enabled=false`

The problem was temporarily solved .

**Comment by ahus1** [comment]
As my development machine is now running on Windows 10 as well, I was able find out how to reproduce this issue: Windows 10, factional scaling and IDE running on JetBrains Runtime 8. 

Starting form release 0.26.20 (currently work in progress) there will be a notification that the preview might be blurry.

The notification links to a Wiki page detailing what to do and workarounds. 

Besides sun.java2d.uiScale.enabled=false the issue seems to be fixed in JBR11 (that is: running the IDE on the JetBrains Runtime 11 that is based on OpenJDK 11). 

Read more about this on the Wiki page: https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview
