### ISSUE TITLE
data-uri images are not rendered in the preview

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-intellij-plugin#229]
Asciidoc supports data-uri, in order to produce single file html document.
However when the doc preview is enabled (with the JavaFX Webrender), images are not rendered.
But The Swing preview browser has the same issue (instead one can see the image placeholder).

I found a trick that allow me to enable `:data-uri:` when the document is not previewed in IJ : 

```
ifeval::[{env}!=idea]
:data-uri:
endif::[]
```
But the plugin should handle it on its own.

AsciiDoc Plugin Version: v0.21.4

IDE Name and Version: 
```
IntelliJ IDEA 2018.3.1 EAP (Ultimate Edition)
Build #IU-183.4588.3, built on November 21, 2018
Licensed to Comuto SA / Brice Dutheil
Subscription is active until July 5, 2019
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

Happened on 2018.3 and older versions too.

**Comment by ahus1** [comment]
Thanks for reporting this. Please post a minimal example document that I can use for tests.

**Comment by bric3** [comment]
Just open this adoc file in IntelliJ with preview enabled.

```adoc
:doctype: book
:icons: font
:source-highlighter: coderay
:toc: left
:toclevels: 4
:sectlinks:
:sectanchors:
:docinfo:
:nofooter:

// Workaround to allow Asciidoc Intellij plugin to render images
// as :data-uri: is not supported at this time https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/229
ifeval::[{env}!=idea]
:data-uri:
endif::[]

:whatever_image: path/to/image.png

image:{whatever_image}[Blablacar]



[plantuml,"oauth-2-client-credentials-flow",svg]
.Oauth 2.0 Client credentials flow
----
title Client authentication
autonumber

user -> client : access public page
----
```

**Comment by ahus1** [comment]
Thanks for the example. I investigated and there seems to be a problem when combining JavaFX and IntelliJ - there is at least one open bug. For now please use the workaround you mentioned. I am not sure when (and if) a workaround or solution might be available. 

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000895600-JavaFX-WebView-in-plugin-and-ClassLoader

https://github.com/javafxports/openjdk-jfx/issues/220

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206767585-Different-ClassLoaders

https://youtrack.jetbrains.com/issue/IDEA-199701

**Comment by ahus1** [comment]
After upgrading to JetBrains Runtime 11 aks JBR 11 this now works as expected.

![image](https://user-images.githubusercontent.com/3957921/59565613-2131a680-9056-11e9-824d-e003ae72e792.png)

See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview how to upgrade to JBR11. 

For 2019.1 this is still experimental, but I read that JBR 11 should be the default for 2019.2

Please try to upgrade. If this introduces new problems, please re-open this issue or raise a new issue. 

On my machine I didn't experience problems with JBR 11, but other have experienced problems with older builds - see #238.

**Comment by bric3** [comment]
Hi, I just wanted to remove my workaround, it seems like JCEF is not working

**Comment by ahus1** [comment]
@bric3 - I assume you want to inline a diagram, but the preview only shows a broken image. I looked into the source code of the latest asciidoctor-diagram and tried the very latest version of the plugin. This is what I found:

My previous analysis for this ticket is no longer valid: since #548 (0.31.25) the JCEF preview has full SVG support, and that revealed through several iterations some issues with Asciidoctor-Diagram, Kroki and the plugin. 

Some are covered in the [plugin's manual](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/diagrams.html) by now. This issue isn't. I'll update after I comment here.

In order to make the diagram work in `data-uri` mode, you'll need to add opts="inline" to each diagram or the svg-type from the next example:

```
[plantuml,"oauth-2-client-credentials-flow",svg,opts="inline"]
```

If you don't have `data-uri` set, you'll need `svg-type="inline"` like this:

```
[plantuml,"oauth-2-client-credentials-flow",svg,svg-type="inline"]
```

I re-opened the issue. Does this comment resolve your issue?

**Comment by ahus1** [comment]
@bric3 - sorry, took the wrong turn. I deleted my previous comment. There have been issues with diagrams, and I'll fix these with JCEF. There will be an update soon.

Sorry again for this comment not matching the question.

**Comment by bric3** [comment]
> sorry, took the wrong turn. I deleted my previous comment.

No problem, it happens to me all the time. ;)

Actually this time this happend with regular image files. I'd like to generate single file reports. Since there is a workaround, this isn't critical.

I believe this is likely related to JCEF, anyway. But I wanted to let you know about this change.

**Comment by ahus1** [comment]
Found it: The JCEF preview has a content security policy. Once I added a the missing entry for data URI it started to work. Now I wait for Travis CI to build a release. Due to Hacktoberfest this might take a while, the build queue for open source projects is quite long at the moment. 

Something I found out recently about the JCEF preview: You can enable the Chromium developer tools, you can then inspect the HTML and see the browser's console. Users have to enable the "internal mode" for that. See the [manual for the latest status](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#benefits-of-the-jcef-preview).

**Comment by bric3** [comment]
Thanks for looking this that quickly ! This wasn't critical  though ;)

> You can enable the Chromium developer tools

Nice ! Thanks for the tip.

Many cheers !

**Comment by ahus1** [comment]
Version 0.31.39 is now available. Please give it a try and let me know if this works for you as expected.

For all who want to give it a try: setting the `data-uri` attribute in a document requires the `allow-uri-read` to be set *in the plugin's settings* (as it is a security relevant attribute and can't be set in a document). 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by bric3** [comment]
Hi, I just tested it, it's working fine, for diagrams and regular images !

However I didn't had to set `allow-uri-read`.
