### ISSUE TITLE
Enable Spell Checking on more block types

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#269]
Currently spell checking is not supported in comments and some block types.

This is to discuss where spell checking should be enabled in the future:

* comments
* sidebar blocks
* quote blocks

(to be continued)

**Comment by mojavelinux** [comment]
I would start with paragraphs (including special ones), comments, and titles.

If you work at the level of the paragraph, then you don't have to worry about something like a quote block because it's either a paragraph itself or contains paragraphs, so you're already covered. Where writers most likely expect spell checking is in the "prose" (which is what we usually call paragraphs).

**Comment by ahus1** [comment]
@mojavelinux - most standard cases are already handled. For IntelliJ I need to tell it on the lexer-token-level what should be spell checked. 

Standard paragraphs, title and titles work already. Paragraphs nested inside blocks delimiters don't work yet, some work with the parser will be required there.

**Comment by ahus1** [comment]
The pre-release 0.26.17 is now available from Github releases. It adds spell check support for the following tokens: 

    AsciiDocTokenTypes.LINE_COMMENT,
    AsciiDocTokenTypes.BLOCK_COMMENT,
    AsciiDocTokenTypes.EXAMPLE_BLOCK,
    AsciiDocTokenTypes.SIDEBAR_BLOCK,
    AsciiDocTokenTypes.QUOTE_BLOCK,
    AsciiDocTokenTypes.LITERAL_BLOCK,
    AsciiDocTokenTypes.BLOCKREFTEXT,
    AsciiDocTokenTypes.LINKTEXT

I've reviewed the list of the tokens and these where the tokens that were missing. Please comment here if any block still misses spell checking.
