### ISSUE TITLE
Author in header leads to wrong re-formatting

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#314]
When adding author and version information to the header of the document, the reformatting scrambles it: it adds an empty line just before the author. Attributes get wrapped to a single line instead of staying in one line.

The plugin should leave the author just below the title. The attributes should stay in their own lines. 

```
= Title
Writer <doc.writer@example.com> v0.1, 2019-01-01
:toc: left
:icons: font
```

AsciiDoc Plugin Version: 0.28.27

(thanks for @luvarqpp for reporting this)

**Comment by ahus1** [comment]
A first analysis shows that the author information is recognized as normal text by the lexer. This leads in the following to treating the attribute definitions as plain text, too, as attributes must not appear within a text block. 

A workaround is to not use the author information or not to use reformatting until this is fixed. 

A user can disable reformatting for AsciiDoc by disabling the checkbox "Settings..." | "Editor" | "Code Style" | "AsciiDoc" | "Enable Formatting".

**Comment by ahus1** [comment]
@luvarqpp - a new preview release 0.29.2 is available that is handling author information and following attribute declarations correctly: it will no longer word-wrap them. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try and comment in this ticket if the pre-releases solves the issue for you. Thanks!

**Comment by luvarqpp** [comment]
@ahus1  thanks, I can confirm that given plugin build is OK in term of formatting author part of document.

Another "magic" has happened through. I have some longer lines (200 and more characters) and I use soft-wrap (sidenote, plugin does not save soft-wrap setting during IDE restarts). After making "code" formatted by plugin (ctrl+alt+L Reformat code, on directory with documents), one line has been split to three lines. Each line after splitting contained single sentence.

I consider given behavior as weird, because the other lines did not get split. Given the single line which has been split has some words in backquote/backtick and it was between two "operation" macro from spring-restdocs-asciidoctor extension (which is in .ascidoctor folder as mentioned in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/310 issue).

**Comment by ahus1** [comment]
@luvarqpp - thanks for giving this release a try.

The one-sentence-per-line is one of the patterns considered an asciidoc best practice. It allows moving around sentences easily, editing the sentence provides you with a meaningful diff view (compared to wordwrap).
Having one line per sentence instead of a whole paragraph keeps the git "annotate" useful to find out who changed what and why.

Having said that this feature can be disabled and enabled separately in the code style settings for asciidoc.

If you have a demo snipped showing some text that was split into two lines but shouldn't, please post it in this ticket. I can the amend the rules.

To make wrapping permanent: there is a general IntelliJ setting that allows you to change to wordwrap for a set of file extensions. The plugin could have given a hint for this I suppose.

**Comment by luvarqpp** [comment]
@ahus1 - you answered all my questions...
I will give it a try (one sentence per line).
Thanks. You can imho close this issue.

**Comment by ahus1** [comment]
@luvarqpp - thank for sharing you experiences. I created to tickets to enhance the UX to learn about conventions and feature "as you go". 

As the original bug is now fixed, I close this ticket.
