### ISSUE TITLE
Figure numbers starts at 2 instead of at 1.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#317]
Asciidoc document

````
= PlantUML Diagram

== Overview

.Class diagram1
[plantuml, diagram-classes, png]
----
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
----

.Class diagram2
[plantuml, diagram-classes, png]
----
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
----

````

is displayed as

![image](https://user-images.githubusercontent.com/13682850/62835223-00e92700-bc56-11e9-8129-e40e4db7a7fe.png)

The number of the first figure starts at 2, instead of at 1. The 2nd figure has number 4 assigned to it, the 3rd figure has number 6 assigned to it, etc. Numbers 1, 2, 3, etc should have been used instead.

AsciiDoc Pugin Version: 
  0.28.27

IDE Name and Version: 
  IntelliJ IDEA 2019.2 (Community Edition)
  Build #IC-192.5728.98, built on July 23, 2019
  Runtime version: 11.0.3+12-b304.10 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  Windows 10 10.0
  GC: ParNew, ConcurrentMarkSweep
  Memory: 2002M
  Cores: 4
  Registry: 
  Non-Bundled Plugins: org.asciidoctor.intellij.asciidoc, PythonCore

**Comment by ahus1** [comment]
Thanks for reporting this. I've probably introduces this bug in when I changed the code to render both PNG and SVG in the background to make it easier to export the images later. I'll look into this issue.

**Comment by ahus1** [comment]
There's now a new pre-release 0.29.4 available that fixes the issue. It was probably introduced in 0.28.5.

Sorry for the inconvenience, thank you for providing an example. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please comment here if you experience any difficulties with this release, or the issue is not resolved.
