### ISSUE TITLE
JavaFX preview not available

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#329]
@ahus1 , thanks for info. I am ow running in EAP version of idea:
```
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 5, 2019
Runtime version: 12.0.2+3 amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 5.0.0-25-generic
```

I am not able to switch to java FX preview (I do not know how). I have tried: File -> Settings -> Languages & Frameworks -> AsciDoc -> Preview browser -> Swing (swing is the only option in combobox)

Have I tried to switch preview engine on right place?

_Originally posted by @luvarqpp in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/312#issuecomment-529344022_

**Comment by ahus1** [comment]
@luvarqpp - I'm moving this to a new issue as it is off topic in the other issue. 

You are using an OpenJDK by Azul Systems. This is most likely missing JavaFX. 

Please use the pre-bundled JetBrains JRE. It should show: 

```
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Once you've setup your IDE to use the pre-bundled JDK, an option for JavaFX should be available: 

![image](https://user-images.githubusercontent.com/3957921/64525764-dbf1dd80-d301-11e9-98c8-1ffcab28d94e.png)

**Comment by luvarqpp** [comment]
Oh, thank This seems to be an issue. I am using [sdkman](https://sdkman.io/), so fixing my problem by issuing `sdk install java 11.0.2-zulufx`, than [change IDE Boot JDK](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under?page=3) for idea by "find action" -> "switch boot jdk" and point it to homerid/.sdkman/candidates/java/11.0.2-zulufx. JavaFX was after ide restart automatically chosen for asciidoc plugin.

If there is missing JavaFX, I would be expect to be aware of "something optional is missing" in settings for asciidoctor plugin. I would probably provide JavaFX as "disabled" option at least in given combobox.

PS: Thanks for solving my issue. No files are now being created in source directories.
PS2: I have noticed that my first chapter is being numbered as 5., instead of 1. I use `:numbered:` attribute and perhaps nothing else special. This could be another issue if you could reproduce it easily. If no, I will raise issue in spare time at the end of week.

**Comment by ahus1** [comment]
@luvarqpp - there should have been an editor notification when you used the extension for the first time. Once you dismiss it, it will not reappear. 

I'll create a feature request referencing your suggestion. 

Please note: zulufx is not the JetBrains JRE. I strongly recommend the JetBrains JRE as this is the one that is tested and supported.

I'll answer on the number issue in the #312
