### ISSUE TITLE
SVG PlantUML diagrams automatically generated

### ISSUE THREAD

**Issue by Kabhal** [asciidoctor/asciidoctor-intellij-plugin#340]
When AsciiDoc document contains a PlantUML diagram configured for a `png` output, the plugin automatically generates all diagrams in `svg` too ...

```
[plantuml,my_diagram,png]
....
      ...
....
```

The plugin should respect the configured attribute.

AsciiDoc IDEA Plugin version 0.30.7

**Comment by ahus1** [comment]
The plugin currently creates both PNG and SVG for the following reasons: 
* the preview in JavaFX (and Swing) doesn't support SVG very well. Therefore it always displays the preview in PNG, no matter what format you originally specified
* You can right-click on the diagrams and save them as images. As you can choose PNG as SVG as target format, it creates both image types in advance. 

Normally you don't see these created files as long as you use the JavaFX preview as they are created in a temporary folder. Actually I recommend you use the JavaFX preview, as it offers the best user experience. 

If creating both files has issues in your environment, please let me know. Otherwise please close the issue. Thanks!

**Comment by ahus1** [comment]
Closed as no reply for more than two weeks. Will be re-opened if an answer is received.
