### ISSUE TITLE
Highlight the content of passthrough block as HTML / CSS /JS

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-intellij-plugin#353]
Hi,

The plugin is already fantastic, and getting better, but I recently had to use some block passthough for some simple html where I didn't want to use include, and I thought this could be a simple welcome enhancement to inject IntelliJ HTML syntax highlighting.

The example above is more complex that what I need to do, but I thought this a is good showcase of the feature.

```adoc
++++
<details>
<summary>
</summary>

<style>
/* some css */
</style>

<script>
/* some js */
</script>

<div>
<video poster="poster.png">
  <source src="video.webm" type="video/webm">
</video>
</div>

</details>
++++
```

AsciiDoc Plugin Version: 0.30.9
IDE Name and Version: IntelliJ IDEA 2019.3 EAP

**Comment by bric3** [comment]
However I wonder if such highlighting would work

```adoc
++++
<details>
<summary>Brief</summary>

include::bigger.html[]

</summary>
++++
```

**Comment by ahus1** [comment]
@bric3 - I think this is a good enhancement. 

Pass through content is not necessarily HTML, but I assume for 99% of the cases it is, and for the rest of the users it will not break things. 

Syntax highlighting with listings is disabled once the block contains an include::[] as I assume the as-is text would be something that can be highlighted correctly; therefore I am hesitant to support the second example. 

The first example should be possible and could build on the existing functionality.

**Comment by mojavelinux** [comment]
> Pass through content is not necessarily HTML

That's true, but it's most likely an SGML language (e.g., HTML or XML).

**Comment by bric3** [comment]
@ahus1 Indeed that seems fair, for the second example.

> Pass through content is not necessarily HTML, but I assume for 99% of the cases it is, and for the rest of the users it will not break things.

Eventually this could be toggled in the settings.

@mojavelinux Thanks for the tip, however wasn't working when assembling the doc with gradle plugin (version 2.3.0), hence I reverted on using the old school pass-through block.

**Comment by mojavelinux** [comment]
@bric3 :+1: Indeed, it's an Asciidoctor 2 feature.

**Comment by ahus1** [comment]
Work started on this feature. Still need to add the configuration menu option to disable it and/or change the language injected for pass through content. Default will be HTML.

**Comment by ahus1** [comment]
This is now implemented and will be part of the next pre-release.

**Comment by bric3** [comment]
cool thanks a lot !

**Comment by ahus1** [comment]
The latest preview-version of the plugin 0.30.22 highlights pass through content. As default it assumes this is HTML. The user can change the language in the plugin settings, or disable it by clearing the field.

![image](https://user-images.githubusercontent.com/3957921/71306622-0fed9c00-23e3-11ea-8fcd-383078952feb.png)

Once the pass through content contains an include macro, it will not be highlighted by the plugin. This is due to the fact that an include:[] is per se no valid HTML, and therefore the block will most likely show errors when trying to highlight it. Suggestions for future enhancement of this behavior are welcome. 

This is part of the latest pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
