### ISSUE TITLE
Integrate JCEF as preview instead of JavaFX

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#390]
In IntelliJ 2020.1 EAP a new browser preview has landed: https://youtrack.jetbrains.com/issue/JBR-1603
This is still experimental. 

The JetBrains Markdown plugin already support for it: https://github.com/JetBrains/intellij-community/blob/master/plugins/markdown/src/org/intellij/plugins/markdown/ui/preview/jcef/JCEFHtmlPanelProvider.java

This could improve the preview capabilities and make it more in-par with current browsers.

More information for users: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/jcef.html

Status of JCEF in IntelliJ Platform: 
* Exceptions in IDE when referenced image is missing - https://youtrack.jetbrains.com/issue/IDEA-241199

Not yet implemented features that work with JavaFX preview:
* mouse wheel to zoom preview
* right-click on image to save

**Comment by mojavelinux** [comment]
At the risk of stating the obvious, this feature has an important impact on the perception (and thus integrity) of this plugin. The only place this plugin currently falls short as an AsciiDoc editor when compared to Atom, VSCode, and Brackets is the preview. Since those other tools are based on Chromium, they provide a preview which faithfully matches what's shown in the browser (and hence what the user expects). We know this is very important to writers.

Being able to offer writers a preview of their work in full fidelity will give them tremendous confidence in this plugin. And that means I'll be able to strongly recommend this plugin to writers, because I know it will provide the very best authoring experience.

I also think this can solve the problem with using the plugin on Linux with a HiDPI screen (which I believe is caused by lack of proper support in JavaFX for Wayland scaling).

**Comment by mojavelinux** [comment]
> I also think this can solve the problem with using the plugin on Linux with a HiDPI screen (which I believe is caused by lack of proper support in JavaFX for Wayland scaling).

I could test the Markdown plugin for you and let you know if it solves this issue.

**Comment by ahus1** [comment]
@mojavelinux - can give examples when the JavaFX preview falls short? Is it for SVGs, for fonts, or for general CSS? IMHO running with a JetBrains JDK the results are good for previewing AsciiDoc as HTML.

If it is about solving a OS specific problem, please consider opening a specific ticket.

JCEF is still preview and not bundled as standard with JetBrains IDEs, so the solution you're looking for here is not around the corner.

**Comment by mojavelinux** [comment]
After a bit of effort to get it set up, I can report that the JCEF browser works flawlessly on Linux with Wayland. The display is sharp and it renders the HTML and CSS as expected.

**Comment by mojavelinux** [comment]
> can give examples when the JavaFX preview falls short? Is it for SVGs, for fonts, or for general CSS?

In general, it looks awful. Here are the things I notice:

* the scaling is incorrect (too large)
* all objects (text and images) are extremely fuzzy
* unicode is not properly supported (you get ??? instead of the character)
* as you mentioned, SVGs are problematic

> IMHO running with a JetBrains JDK the results are good for previewing AsciiDoc as HTML.

Not for the reasons I cited. Based on what I'm seeing, the preview serves little purpose.

I'd be happy to prepare some screenshots tomorrow.

> JCEF is still preview and not bundled as standard with JetBrains IDEs, so the solution you're looking for here is not around the corner.

It takes a bit of effort to get set up, but it can be enabled and used just as it is in the Markdown plugin. (See https://youtrack.jetbrains.com/issue/IDEA-231833#focus=streamItem-27-3993099.0-0 for instructions) I'd be willing to do that to get a decent preview.

**Comment by mojavelinux** [comment]
> unicode is not properly supported (you get ??? instead of the character)

Here's a screenshot from the Antora docs:

![javafx-unicode-problem-resized](https://user-images.githubusercontent.com/79351/80841049-dd875300-8bbb-11ea-896e-623faa911305.png)

It could be lack of support for fallback fonts, or that those glyphs are in the font being used for the preview. Hard to say.

**Comment by mojavelinux** [comment]
> all objects (text and images) are extremely fuzzy

This is solved by https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview

**Comment by mojavelinux** [comment]
> the scaling is incorrect (too large)

This might actually just be that the built-in stylesheet is using fonts which are too large. It might be nice to be able to set the base font size in the setting, or have a block for custom CSS like the Markdown preview has.

**Comment by mojavelinux** [comment]
> Based on what I'm seeing, the preview serves little purpose.

With the fuzzy text / object problem solved, it's much more usable.

**Comment by ahus1** [comment]
> all objects (text and images) are extremely fuzzy / This is solved by https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview

There is now an editor notification that shows for Linux users with Display scaling activated. It directs them to the recipe to apply the setting to fix this. 

![image](https://user-images.githubusercontent.com/3957921/80860035-71612980-8c65-11ea-953a-34f66a228c74.png)

> the scaling is incorrect (too large)

The very lastest version of the plugin has an option to scale the preview. This was first suggested by Dan Haywood in #444. The default is still 100%, I haven't yet decided to change it for example to 90% by default.

![image](https://user-images.githubusercontent.com/3957921/80860058-a79ea900-8c65-11ea-8068-d82aa83c8c34.png)

This ticket will continue to focus on a JCEF integration. Please direct topics related to JavaFX to new GitHub issues.

**Comment by mojavelinux** [comment]
> There is now an editor notification that shows for Linux users with Display scaling activated.

Thanks!

> I haven't yet decided to change it for example to 90% by default.

This is a neat option, but it's kind of a brute force way to solve the font size being too large by default. In most cases, it's better to set the root font size in CSS and use that to control the size of text and spacing. But since this issue is not about that, I'll wait to discuss that in a future issue related to zoom.

**Comment by ahus1** [comment]
As of IntelliJ 2020.2 EAP (#IC-202.4357.23) the JetBrains runtime now includes the JCEF browser. I still had to set "ide.browser.jcef.enabled" to "true" in the registry manually, although https://youtrack.jetbrains.com/issue/IDEA-240461 indicated this wouldn't be necessary any more.

**Comment by ahus1** [comment]
Version 0.31.3 is available with AsciiDoc JCEF preview browser support. You'll need the latest 2020.2 EAP (202.5103.13) version to try it. In this version JCEF seems to be enabled by default in the platform (no need to set the "ide.browser.jcef.enabled" in the registry any more). 

In order to try it with the AsciiDoc plugin users need to switch the preview:

![image](https://user-images.githubusercontent.com/3957921/83939556-39a64e00-a7de-11ea-9054-d79723299492.png)

This is an early preview to receive feedback on errors and glitches. Be prepared for a rough ride.

Current status known issues/not yet implemented features (list will be updated in issue's description above):

Status of JCEF in IntelliJ Platform: 
* Exceptions in IDE when referenced image is missing - https://youtrack.jetbrains.com/issue/IDEA-241199

Not yet implemented features that work with JavaFX preview:
* mouse wheel to zoom preview
* right-click on image to save

**Comment by ahus1** [comment]
The latest IntelliJ EAP version doesn't show exceptions on missing images any more. 

Mouse-wheel zoom and right-click-on-generated-image-to-save work. 

I therefore close this ticket as it is in-par in terms of features with the JavaFX preview. SVG preview and CSS should be superior due to the embedded Chrome based browser.

JCEF is still marked experimental as there might be early bugs and missing edge-cases.
