### ISSUE TITLE
Autogenerate missing anchors for headers

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#427]
As discussed in #421, it's best practice currently to specify explicit anchors for headings.

This ticket is the simple requirement, to allow any missing headers to be automatically generated.  This could be done using either/both of:

a) integrated with Code > Reformat Code (perhaps a config in Editor > Code Style > Asciidoc)
b) on demand, eg ctrl-shift-enter on a heading

The generated anchors should be consistent with any asciidoctor prefixes.  In Antora, these are determined by:

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"

(not sure what/if experimental is relevant, but the other two are).

**Comment by mojavelinux** [comment]
As it stands now (and has for a long time), experimental enables UI macros, nothing more.

**Comment by danhaywood** [comment]
Could you provide a link to a doc on UI macros so that I know what they
are, exactly?

**Comment by mojavelinux** [comment]
https://asciidoctor.org/docs/user-manual/#user-interface-macros

**Comment by ahus1** [comment]
The next version of the plugin will have an inspection that warns the user that an anchor points to an automatically generated ID of a section. The quick-fix available with Ctrl+Enter will add a block ID to the section. 

Another inspection will highlight if the file or anchor reference doesn't resolve. Anchors are case sensitive. If the broken anchor can be fixed by changing the case of the anchor, then this is provided as quick-fix.

A user can change the severity of the inspection in their local settings.

![checklinks](https://user-images.githubusercontent.com/3957921/77235754-c9ae0180-6bb8-11ea-9de5-0f6ba9736dc4.gif)

**Comment by ahus1** [comment]
Hello Dan / @danhaywood, a new pre-release 0.30.45 is available. 

It finds most problems with unresolvable anchors and links. Please give it a try on the ISIS documentation. 

For now for local links only supports `xref:#anchor[]` (with hash), not yet `xref:anchor[]` (without hash). I'll fix this in the next release.

I ran "Analze | Inspect Code..." with an inspection profile for only AsciiDoc; this highlighted several broken links in the ISIS documentation. If it is only a case issue in an anchor, the plugin suggests a fix.

If you find false positives besides the xref anchor issue described above, please comment in this ticket.

**Comment by danhaywood** [comment]
Tried it out, no issues so far, very nice implementation.  I think this
works great.

It made me think of another small feature. ... when I write a new heading,
it would be nice to have an anchor available as a quick tip (alt-enter).
I'll raise a different ticket for that, this one is done I think.

**Comment by ahus1** [comment]
I'm happy to hear that it works for you.

**Comment by ahus1** [comment]
Pre-release 0.30.46 has been released that supports local xrefs with xref:anchor[] correctly.
