### ISSUE TITLE
How to configure the fonts?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-intellij-plugin#455]
I want to configure the fonts.  Could I configure the fonts?

----
I write a theme for Asciidoctor PDF. And I config the font in the theme. Then Asciidoctor PDF can deal with Chinese chars.

So, I think If I configure the Chinese fonts, the plugin maybe can deal with Chinese chars.

@ahus1 Is it clear enough?

**Comment by ahus1** [comment]
I assume you want to configure fonts for the preview? 

The current way to configure fonts (or any custom CSS) for the preview is to add a snippet of CSS into a ".asciidoctorconfig" file in the root of the project like this: 

```
// .asciidoctorconfig
++++
<style>
body {
font-family: "Comic Sans MS", "Helvetica"
}
</style>
++++
```

Benefit: you can check-in this configuration as code, and everyone else who opens the project will use the same configuration.

See the wiki chapter [project specific configurations] (https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations) for more information.

**Comment by diguage** [comment]
> I assume you want to configure fonts for the preview?
> 
> The current way to configure fonts (or any custom CSS) for the preview is to add a snippet of CSS into a ".asciidoctorconfig" file in the root of the project like this:
> 
> ```
> // .asciidoctorconfig
> ++++
> <style>
> body {
> font-family: "Comic Sans MS", "Helvetica"
> }
> </style>
> ++++
> ```
> 
> Benefit: you can check-in this configuration as code, and everyone else who opens the project will use the same configuration.
> 
> See the wiki chapter [project specific configurations] (https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations) for more information.

Let me try it. 

I want to add Chinese fonts for the plugin. Chinese chars are not dealt with.

**Comment by ahus1** [comment]
@diguage - the snippet I posted above will only work for HTML output and HTML preview. It will not work for the ruby/prawn based asciidoctor-pdf.

asciidoctor-pdf uses ttfunk 1.5.1 and requires TTF fonts to work. I had a look at https://github.com/adobe-fonts/source-han-serif and only found OTF fonts, also some TTC fonts. I gave them a try but they didn't work ("NoMethodError: (NoMethodError) undefined method `key?' for nil:NilClass") as described in the example https://github.com/ahus1/asciidoctor-deepdive/blob/master/manual-zh_CN/css/zh_CN-theme.yml

There is a different project based on JavaScript/Chrome called asciidoctor-pdf.js by @Mogztter: https://github.com/Mogztter/asciidoctor-pdf.js
I gave it a try and it can use the "Source Hans Serif" fonts (after they are installed locally). I extended the example: https://github.com/ahus1/asciidoctor-deepdive/tree/master/manual-zh_CN

In order to make it work, use the following steps - see a screenshot for an example output below: 
1. install all necessary fonts locally, so a locally installed browser can find them
2. create a file package.json like in the example to instruct yarn what to do
3. create a file custom.css like in the example to configure the fonts you want to use
4. install node and yarn
5. run "yarn install" once to download the dependencies
6. run "yarn render" to create the PDF

optionally: run "yarn preview" to inspect the layout/CSS

Please note: 
1. this plugin uses the ruby/prawn based version. To create a PDF with the JavaScript/Chrome based version you'll need to run an external command.
2. for questions about asciidoctor-pdf.js, please direct them in its own GitHub project https://github.com/Mogztter/asciidoctor-pdf.js 
3. It is still an alpha version, some of the things that work for asciidoctor-pdf might not yet work for asciidoctor-pdf.js. The start page of the repository might list command line options and functionality that is not yet available in a released version; make sure to switch to the latest release branch (currently alpha-7). 

*Sample screenshot of some asciidoctor-pdf.js output:*

![image](https://user-images.githubusercontent.com/3957921/79112787-acb3bb00-7d7f-11ea-916d-1dfc4a30bfe4.png)

**Comment by ahus1** [comment]
@diguage - I just saw that the examples you showed where from https://github.com/diguage/jdk-source-analysis and that you found some TTF fonts for Source Han Serif.

To make the PDF-generation work with the AsciiDoc IntelliJ plugin, add the attributes pdf-fontsdir, pdf-stylesdir and pdf-theme.

I tried to add it to _attributes.adoc, but it only worked when the include was placed before the first headline, not if it was placed below. 

If you don't want to include this file in every document, consider adding a .asciidoctorconfig file instead. 
See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations for more information how this can help.

```
// docs/.asciidoctorconfig
// this adds attributes to every preview being rendered in IntelliJ

:pdf-fontsdir: {asciidoctorconfigdir}/../cfg/fonts
:pdf-stylesdir: {asciidoctorconfigdir}/../cfg/theme
:pdf-theme: Source
```

See below for an example output. 

![image](https://user-images.githubusercontent.com/3957921/79115659-b7258300-7d86-11ea-8ff3-ec3e173d81dc.png)

**Comment by diguage** [comment]
The solution is very great. Thanks.

**Comment by ahus1** [comment]
I distilled the contents of this discussion for the plugin's documentation: 

* [Creating PDFs for non-latin languages and extra fonts](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/pdf-non-latin-languages.html)
* [Custom stylesheets for the preview](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html)

As this task is complete, I close this issue. If you find the docs incomplete, please create an issue or a pull request with updated docs.

**Comment by diguage** [comment]
> I distilled the contents of this discussion for the plugin's documentation:
> 
> * [Creating PDFs for non-latin languages and extra fonts](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/pdf-non-latin-languages.html)
> * [Custom stylesheets for the preview](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html)
> 
> As this task is complete, I close this issue. If you find the docs incomplete, please create an issue or a pull request with updated docs.

Wonderful! It is a great task. Thank you very much.

**Comment by yangbo** [comment]
> I distilled the contents of this discussion for the plugin's documentation:
> 
> * [Creating PDFs for non-latin languages and extra fonts](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/pdf-non-latin-languages.html)
> * [Custom stylesheets for the preview](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html)
> 
> As this task is complete, I close this issue. If you find the docs incomplete, please create an issue or a pull request with updated docs.

I found it is possible to use Windows default fonts, so that we can do not copy the huge font files.

Example:

`= Test Title
:pdf-themesdir: themes
:pdf-theme: windows
:pdf-fontsdir: c:/Windows/Fonts/
`

The 'windows-theme.yml' content:

`# default theme at https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml
extends: default
font:
  fallbacks:
    - simkai
  catalog:
    # use windows fonts 'DengXian', better than 'simkai, simfang.ttf'.
    deng:
      normal: Deng.ttf
      bold: Dengb.ttf
      italic: Dengl.ttf
      bold_italic: Dengb.ttf
    simkai:
      normal: simkai.ttf
      bold: simkai.ttf
      italic: simkai.ttf
      bold_italic: simkai.ttf
    Noto Serif:
      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf
    # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
base:
  font_family: deng
`
