### ISSUE TITLE
Does not seem to pick up JavaFX for OpenJDK11 64bit

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#464]
Do I need to do a separate download of JavaFX?  The docs suggest not if I am using the inbuilt OpenJDK11 from JetBrains.  However, I AM using that JDK and I get the error, so something is awry.

the message I see:

![2020_04_23_12_40_13_setup_dev_env](https://user-images.githubusercontent.com/1031625/80095979-c4015e00-8560-11ea-99fe-2472c5e9a9b6.png)

The version I am on:

![2020_04_23_12_40_46_](https://user-images.githubusercontent.com/1031625/80096014-d380a700-8560-11ea-96b6-2dcc15eb665b.png)

If I switch back to JDK8 64bit, all is well again.

**Comment by ahus1** [comment]
Up until today all JetBrains JDKs contained JavaFX. Some JetBrains-Plugins like the Markdown-Plugin already use this as well and break when this is not installed. 

I've raised an issue with JetBrains: https://youtrack.jetbrains.com/issue/IDEA-238684

**Comment by ahus1** [comment]
Update on this: there is a description on how to install the "Choose JVM" plugin, and then install a specific version of the JetBrains JDK of your choice: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

On Windows I installed the latest JBR 11 build. See screenshot below. Now the AsciiDoc plugin works as expected. 

**TODO**: update notification, update wiki

![choose-jvm](https://user-images.githubusercontent.com/3957921/80236682-c3012700-865b-11ea-841a-10afdb3fcd8d.png)

**Comment by mojavelinux** [comment]
I'm very interested in this workaround. I just tried the plugin on Fedora 31 w/ Wayland and the preview looks really awful (through no fault of the plugin). The objects are scaled by about 2x and are very fuzzy. I'm hopefully using a newer JDK will solve the issue. I'll report back once I try it.

**Comment by ahus1** [comment]
@mojavelinux - the recommended installation on any OS (Windows, Linux, MacOS) is to use the JDK pre-bundled with the IDE. When you download the IDE from JetBrains, JDK 11 is the default (and the recommendation for the plugin). See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/JavaFX-preview for more information. 

This issue is about an yet unresolved situation where the pre-bundled JDK didn't include JavaFX. It it still to be discovered why this is the case. Installing a different JetBrains JDK as described above will fix it, but should not be the standard procedure.

**Comment by ahus1** [comment]
@mojavelinux I've installed Fedora 31 (as a VirtualBox image from osboxes.org) and downloaded IntelliJ CE 2020.1.1 from the JetBrains Website as tar.gz. This includes a JetBrains JDK runtime. Then I added the AsciiDoc plugin in version 0.30.59.1

This is the result. I don't see font artifacts and they are not blurry. Please share your experiences/screenshots/settings so I try out solutions.

![image](https://user-images.githubusercontent.com/3957921/80803129-a3b14f00-8bb1-11ea-9442-608de4e1ea08.png)

**Comment by mojavelinux** [comment]
The problem is specifically when using Wayland with text scaling (200% in monitor configuration).

But even based on your screenshot, I don't find the text rendering to be clear. I know these fonts very well and that's not how they are supposed to look. The antialiasing, kerning, and stem directions are all off.

**Comment by mojavelinux** [comment]
> This issue is about an yet unresolved situation where the pre-bundled JDK didn't include JavaFX.

Then that doesn't apply to my situation since JavaFX is enabled for me. Though I do wonder whether Java 14 is any better.

**Comment by ahus1** [comment]
Thanks for pointing out the 200% text scaling. I applied this and then saw the blurry preview. 

I then applied the recipe https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview and this lead to an un-blurred preview. See screenshot below. 

I'll update the recipe that is helps for font scaling on Fedora/Wayland.

![image](https://user-images.githubusercontent.com/3957921/80804802-90ed4900-8bb6-11ea-851c-c61d67202d37.png)

**Comment by mojavelinux** [comment]
@ahus1 I'm happy to report that the JVM option you suggested fixes the blurry text an objects problem when using Wayland scaling. Thank you for that suggestion. That makes the preview usable.

> I don't find the text rendering to be clear. I know these fonts very well and that's not how they are supposed to look.

I partially retract this statement because I now realize the preview doesn't use the fonts from the default stylesheet. That explains why they don't look familiar to me. However, I still don't think the rendering is as clear as it is in Chrome and Firefox.

Here's a screenshot of the unicode problem from the Antora docs:

![javafx-unicode-problem-resized](https://user-images.githubusercontent.com/79351/80840863-78336200-8bbb-11ea-82f9-b4f24d5c6c6e.png)

Some I'm still really interested in having the JCEF browser option (#390).

**Comment by ahus1** [comment]
I updated to the latest version of DataGrip. This includes a JBR with JavaFX. The AsciIDoc plugin preview for JavaFX now like on any other IntelliJ based IDE..

DataGrip 2020.1.4
Build #DB-201.7846.70, built on May 28, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

This runtime also includes some javafx-files, where the original one didn't. 

Therefore I consider this issue fixed.
