### ISSUE TITLE
Asciidoc unconstrained formating syntax not properly supported in the editor.

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-intellij-plugin#528]
The editor pane does not stop correctly the bold style, when using asciidoc unconstrained formatting syntaxt.

```adoc
The JVM identified two **E**quivalent **M**odulo **C**onstant **P**ool methods (i.e. the original method and
the method I just modified).
```

![image](https://user-images.githubusercontent.com/803621/88678326-a0fdc180-d0ee-11ea-9f11-f7ef86977f4a.png)

I would have expected the style to only be applied to the formatted letters, here : E, C M P.

It's probably worth another issue, but would it be possible to ask grazie or the spellchecker to ignore the unconstrained syntax to analyze the word ?

-----

AsciiDoc Plugin Version: 0.30.86
IDE Name and Version: 2020.1.4
```
IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Licensed to Comuto SA / Brice Dutheil
Subscription is active until January 22, 2021
Runtime version: 11.0.7+10-b765.65 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.github.b3er.idea.plugins.arc.browser, com.github.weisj.darkmode, Lua, intellij.indexing.shared, GrepConsole, JOL, Lombook Plugin, com.intellij.bigdecimal-folding, org.jetbrains.plugins.spotbugs, com.mallowigi.idea, com.thvardhan.gradianto, intellij-clock, jd-intellij, lermitage.intellij.battery.status, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.file-preview, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, com.intellij.kubernetes, Pythonid, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.jetbrains.packagesearch.intellij-plugin, org.asciidoctor.intellij.asciidoc, org.toml.lang, org.rust.lang
```

**Comment by ahus1** [comment]
Thanks for reporting this. The next version will highlight unconstrained formatting properly in the editor.

Regarding the green squiggly line: 
The IDE has two APIs, both add the green squiggly line: one for the spellchecker, on for Grazie grammar checker. 

The current naive spell checker assumes that a word can't consist of more than one token. The grammar checker offers an API to remove tokens (or a part of it) from the text "seen" by the plugin. Both APIs have their their limitations. 

I tweaked the spell checker code a bit that it tries to summarize tokens before passing them to spell checking. This is the result: 

![image](https://user-images.githubusercontent.com/3957921/88955191-df84af00-d29b-11ea-999f-ec82a5134899.png)

Conditions: 
* it needs to be part of a block or section to work (otherwise it currently doesn't have a parent element that can combine its children)

Result: 
* You example is not recognized as "spelled correctly" 👍 
* "Probleem" has one "e" too much, therefore it is recognized as spelled incorrectly 👍 
* As the two "**" have been removed, the green line is two chars too short  
* Users shouldn't try to accept the suggested word, as this would replace the text to "**Problemem" (that is: removing the second "**" and keeping two chars at the end of the line)

It will need a bit of tuning to classify tokens in those that are "printable" and that separate words (like "->") and those that are "not printable" and therefore don't separate words (like "**").

What do you think - it is an improvement from your point of view?

Would you want to give it a try? Let me know if you want to receive a pre-release for 2020.1 or 2020.2.

**Comment by bric3** [comment]
Wow, cool !

**Comment by ahus1** [comment]
I created an issue in the IDEA issue tracker for the API to evolve: https://youtrack.jetbrains.com/issue/IDEA-247205

**Comment by ahus1** [comment]
There's pre-release 0.31.17 that includes these changes. Please give it a try and let me know where I missed corner cases. I'll leave this issue open for some days before I close it.

IntelliJ 2020.2 is needed to run this plugin version.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by bric3** [comment]
For me it works as expected, so it's really good. I've e noted a variation of the last point

> * As the two "**" have been removed, the green line is two chars too short
> * Users shouldn't try to accept the suggested word, as this would replace the text to "Problemem" (that is: removing the second "" and keeping two chars at the end of the line)

Writing `**p**oiters` will highlight the word in gree up to `e` included, and when replacing the word, IJ replaces the word up to `e` as well, leaving the fixed string as `**pointersrs`.
I wonder if this will lead to some confusion and more bug reports. Maybe this orthographic feature should be marked as experimental.

**Comment by ahus1** [comment]
Thanks for trying it. I'll keep it enable by default as it will show less false-positives in spell checking.

Regarding corrections for spell checkers: There is one more API that I can implement. The [consumeToken()](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/AsciiDocSpellcheckingStrategy.java#L102) supports a "replace" mode, and this might be able to keep existing `**` elements. Let's see; I'll keep this issue open.

**Comment by ahus1** [comment]
Thanks for watching this closely, you found a regression! 

The "." was not passed to the Grammar check correctly, and the grammar checker suggested to change "too the" to "to the". Analyzing this I found that cell contents were neither spell- nor grammar-checked. Oops!

Pre-release 0.31.18 is now available that fixes these regressions. 

Some background: The "too ... The" is highlighted by the grammar checker, not the spell checker. You can see this when looking at the warning as it displays "Powered by LanguageTool": 

![image](https://user-images.githubusercontent.com/3957921/89434330-b6549a80-d743-11ea-9569-dfcdb2aa3822.png)

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by bric3** [comment]
Cool ! This looks good after the `.18` build. Thnak you for the quick update !

**Comment by ahus1** [comment]
Thanks for trying out this pre-release. 

I looked into the "replace" mode, but to me it doesn't match the use case of changing a word spanning multiple tokens. Therefore I'll wait for the API change in IntelliJ. 

I'm watching the IntelliJ issue and will receive a notification once it's ready. Therefore I close this issue.

If you find any issue related to this topic, please let me know.

**Comment by bric3** [comment]
Sure :) I retweeted this ticket to IntelliJ. Hopefully this will speed up this process.
Thank you :)
