### ISSUE TITLE
attribute defined in toplevel document and used in an include statement in an included document will break include

### ISSUE THREAD

**Issue by dirkhusemann** [asciidoctor/asciidoctor-intellij-plugin#572]
Setup:

* top-level `doc.adoc` containing an attribute definition `subsystems`:
```
= Test
// doc:
:subsystems: sub

[source,yaml]
----
include::{subsystems}/a.yml[]
----

include::b.adoc[]
```

* top-level `b.adoc` containing an include using the `{subsystem}` attribute defined in `doc.adoc`:
```
== B

[source,yaml]
----
include::{subsystems}/a.yml[]
----
```

* plus, a YAML file in `sub/a.yml`:
```
title: test
  subtitle: subtitle
```

*Observed Behavior*

When using the attribute in the `include::` statement, the plugin does apparently know about it, as it offers the correct path completion for `a.yml`. As soon as the closing `[]` are added, however, the plugin flags the whole include-statement as flawed, stating the it cannot find the include file and in the mouse-over showing the unexpanded path. The preview of `b.adoc` shows an error where the include should take place.

The preview of the top-level `doc.adoc` is fine, no errors are shown.

*Expected Behavior*

Similar to reference I'd expect the plugin when in sub-doc `b.doc` to know about the top-level attributes --- which, tantalizingly, the plugin appears to do when offering path completion, but then forgets about once the closing `[]` are added.

AsciiDoc Plugin Version: 0.31.33

IDE Name and Version: PyCharm 2020.2.3 (Professional Edition)
Build #PY-202.7660.27, built on October 6, 2020
Licensed to XXXXXXXX

Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.19.0-11-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 964M
Cores: 4
Non-Bundled Plugins: PlantUML integration, com.andrewbrookins.wrap_to_column, name.kropp.intellij.makefile, org.asciidoctor.intellij.asciidoc, com.jetbrains.intellij.datalore, com.intellij.swagger
Current Desktop: Undefined

**Comment by ahus1** [comment]
Thanks for reporting this. 

Reading your description the plugin is right to "guess" that the attribute "{subsystems}" resolves to "sub" during typing as there is probably only one definition of this attribute in your project. 

The preview is then rendered considering the page standalone, without this assumption. All errors that occur rendering the preview are shown in the editor.

The current implementation considers "guessing" to be OK for autocomplete, but NOT OK for rendering a preview. 

Instead of the IDE guessing about attributes for rendering, I suggest you add a file `.asciidoctorconfig`. Place it in your documentation folder. It can contain all attribute configuration you would like to have for rendering a preview. It will be prefixed before rendering to all files in that folder and its subfolders.

```
// .asciidoctorconfig
:subsystems: sub
``` 

Read more about it in the user guide: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

Please let me know if works for your scenario.

**Comment by ahus1** [comment]
I close this issue as there has been no comment for the last three weeks. If you have further questions, please comment here and I'll re-open the issue.
