### ISSUE TITLE
regression on xref lookup completion in 0.31.35

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#577]
Might just be me, Alexander, but at any rate file name -completion (ctrl-space) seems to be broken in 31.35.  I reverted to 31.34 and that immediately worked again.

I notice in 31.35 release notes that there was some work done in the space of xref's, so perhaps it's a regression.

**Comment by ahus1** [comment]
Ups, thanks for reporting this issue while it as still in EAP. Good to have you around giving them a test run. Expect a new EAP version soon.

**Comment by ahus1** [comment]
This has been fixed in 0.31.36. A local test showed that autocompletion for xrefs now works again as expected. Therefore I close this issue. If you still experience the problem, please comment here and I'll reopen the issue. If you experience other problems, please open a new issue.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
