### ISSUE TITLE
Rename file with include directive in Antora project

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#599]
> At the moment only Shift-F6 (rename file) is supported

I tried to do that with an include directive that uses partials from antora, and I found it renames the file inside partials directory, but not the directive content. Is that intended?

_Originally posted by @abelsromero in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/558#issuecomment-730679658_

**Comment by ahus1** [comment]
I moved this to a new issue, as it seems to be unrelated to moving a file. 

Could you please fill in the details for a bug issue ([see template](https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/master/.github/ISSUE_TEMPLATE/bug.md)) including an example? Thanks!

**Comment by abelsromero** [comment]
## Observed vs. expected behavior

Currently it is possible to use the "Refactor > Rename..." (Shift+F6) feature when the cursor is on an include (tested with norma and partial includes in antora) to rename it.
![image](https://user-images.githubusercontent.com/5781153/99776100-97bab980-2b10-11eb-9c11-cf17da28481c.png)

However, this will only rename the file, but not the content of the include directive, so the user must rename it manually.

I would expect that when this feature is used, the include content would also be renamed.
For consistency, other ocurrences of the same include should also be rename (if possible).

## Steps to reproduce

1. Create an antora project
2. Include write a valid include.
3. Place cursor in the include and press 'Shift+F6' (Linunx or Win)
3. Rename the file in the popup presented by intellij.

## Environment


Plugin Version: 0.31.42


IntelliJ Details:
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.9.3-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1937M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Lombook Plugin, org.toml.lang, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc, org.rust.lang
Current Desktop: Undefined

**Comment by ahus1** [comment]
Hello @abelsromero, thanks for providing all the details. 

Looking at the screen shot, I see that the checkbox "Search for references" is unchecked. 

Once the checkbox is checked, renaming a file (using the dialog, or using the renaming on the file itself) will rename all references. Usually "Project scope" is the right (and default) scope unless you want to restrict renaming on the any other scope. 

Please give it a try, I assume this solves your issue.

**Comment by abelsromero** [comment]
> Please give it a try, I assume this solves your issue.

Yes, it's working, thanks! Including references in other files.

Haven't realised because when refactoring Java code there's not extra window and these option is applied by default. I mean...who ever reads popups :roll_eyes:

**Comment by ahus1** [comment]
> when refactoring Java code there's not extra window

I admit I haven't looked into the details on how to avoid the extra popup.

> I mean...who ever reads popups

True! 

Thanks for providing the fast feedback. It seems that only I can close the issue as I opened it. Closed!
