### ISSUE TITLE
Privacy information

### ISSUE THREAD

**Issue by kst83** [asciidoctor/asciidoctor-intellij-plugin#669]
## Description

I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by ahus1** [comment]
Thanks for asking this question. This comment tries to give a first idea to give you an idea. 

To add the privacy information to the documentation some more work would be required. You could help by asking the right questions and engage in a discussion. As I assume you are looking for your employer/company to approve it, you might have access to experts that could help in one way or another. 

The privacy page in the docs you look for would be a result of such a process. This is a community project with a growing user base. Still, it is a spare time project that is happy to accept contributions of any kind.

Please let me know how you want to proceed.

The good news:
* The plugin doesn't use tracking and will not collect statistical information about the user or content you edit. 
* The plugin has been designed in a way that you can edit content on your local PC and the preview will be rendered locally as well. 

Some things you should still consider:
* If the content you edit includes a remote image, the preview will pull that image from the internet and will reveal your IP address. I'm not a lawyer, but AFAIK people consider IP addresses as personal information in the EU. 
* If you choose to use Kroki diagram preview instead of Asciidoctor Diagram, the contents of your diagrams will be transmitted to a Kroki server and rendered there. You can choose to host your own Kroki server.
* In general you should only edit trusted content in your IDE. If you choose to check an untrusted project and choose to edit it, the code of that project might contain malicious snippets as part the AsciiDoc content and other scripts. 
* When you use the plugin's users guide on the web, the web hoster will receive your router's IP address and store them for up to 30 days. 
* If an exception occurs in your IDE and IntelliJ attributes the exception to the AsciiDoc plugin, the user can choose to send information about the exception to the plugin's Sentry service. The user can (and should) review the information before submitting it. It may contain personal information if it is part of the exception's message, or if the user chooses to enter personal information in the error description. It also contains information about the IDE version, the OS version, a list of other plugins installed in the IDE and standard information Sentry adds. 

This list is probably incomplete, but these are the major points that I can think of at the moment.

**Comment by kst83** [comment]
Thanks, the information you posted is exactly what I was looking for!

**Comment by ahus1** [comment]
The essence of this thread is now part of the plugin's docs: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/privacy.html
