### ISSUE TITLE
Preview document link navigation broken in 0.32.50

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#768]
Clicking on a section title or subsection title in the Preview window causes the Source window to display the corresponding Asciidoc source text. This works in the Asciidoc plug-in up to 0.32.49, but is broken in 0.32.50.

IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Non-Bundled Plugins: Batch Scripts Support (1.0.12), CMD Support (1.0.5), com.github.lppedd.idea-conventional-commit (0.18.0), de.docs_as_co.intellij.plugin.diagramsnet (0.1.7), EclipseCodeFormatter (20.8.203.000.0-Eclipse_2020-06-JavaOnly), com.dubreuia (2.2.0), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), org.mapstruct.intellij (1.2.4), PythonCore (211.7142.45), org.asciidoctor.intellij.asciidoc (0.32.50)
Kotlin: 211-1.5.0-release-759-IJ6693.72

**Comment by ahus1** [comment]
I'm sorry this has happend. Thanks for tracking down the version where this broke. I'll look after it.

**Comment by ahus1** [comment]
I was able to reproduce the issue and fix it. 

The fix is included in release 0.32.50. It should be available from the JetBrains marketplace within a few minutes. 

You can also download it from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) to install it manually.

As I was able to reproduce the problem and the fix, I close this issue. If a problem persists, please comment here and I'll reopen the issue.
