### ISSUE TITLE
Antora xref text does not resolve attributes in preview

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-intellij-plugin#889]
## Observed vs. expected behavior

In Antora an `xref` to a page uses the `reftext` of the page in question as the hyperlink text. If the `reftext` of a page contains an attribute reference, the preview in IntelliJ will not resolve this attribute reference. Instead the `{attribute}` reference is displayed literally.
When rendering the site using Antora, these references are fully resolved (even transitively) and the expected text is displayed instead of the attribute reference.

## Steps to reproduce

- Create a page with a an attribute `:attribute: foo` and `:reftext: {attribute}`
- Create another page with an `xref` to the first page.

## Environment

Plugin Version: 0.35.8

IntelliJ Details: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Licensed to Cerris BVBA / Pepijn Van Eeckhoudt
Subscription is active until November 8, 2021.
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins: org.antlr.intellij.plugin (1.16), com.jetbrains.upsource (2020.1.1924.11), org.asciidoctor.intellij.asciidoc (0.35.8), PlantUML integration (5.6.0), org.jetbrains.plugins.ruby (212.5284.19), Pythonid (212.5284.44), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), JProfiler (19.3), com.intellij.gwt (212.4746.52)
Kotlin: 212-1.5.31-release-546-IJ4638.7

**Comment by ahus1** [comment]
Thanks for reporting this. As the plugin mimics Antora's behavior, it is sometimes slightly off. Whenever that happens, the plugin aligns. 

The case you described above will work.
Please note that resolving attributes within the plugin uses some heuristics (not Antora of course). They work best when an attribute is defined with one value, and not with different values within the scope. If it is defined with different values, the plugin might decide that it is not sure about the result, and will not replace it. 

If you have a publicly available example, please share a link so I can test it.

I pushed a commit and it will be fixed in the upcoming release. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.35.9 is now available that includes this change. Please give it a try if it works as expected.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
Pre-release 0.35.10 is now available that I tested with the example you provided. Please give it a try. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
