### ISSUE TITLE
Create Table Dialog improvements?

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-intellij-plugin#92]
Hi,

I began messing around with the create table dialog. Before I put much more effort into that (and make it so that I can make a PR for that) I would like to know what you think about it.

What I done so far is to replace the check box for the title with a text field for the title, so that this can be entered directly in the dialog. Not typing anything there (empty string) is equal to not checking the box.

What I would like to work on is to allow some data-entering in a spreadsheet-like way. Not sure how to do that yet, my skills in swing are quite rusty, but I think this could be a fun task and I think it would improve the UI.

So, what do you think about that?

**Comment by bodiam** [comment]
Hi @sputnik27 ,

Both ideas seem like a good idea. Maybe you could make it two pull requests, because the first one seems trivial, the second a little less.

For the second one, I'm not 100% sure how the end result should look, but you could think of reusing the rows and columns spinner, and based on that, create a spreadsheet like grid of textfields. You could then also move the 2 spinners next to the textfield. Something like this:

````
+----------------------------------------------------------------------------+
|                                                                            |
|   +-------------------------------------------+       +----+        +----+ |
|   | <title>                                   | rows  | 6  |   cols | 5  | |
|   +-------------------------------------------+       +----+        +----+ |
|                                                                            |
|                                                                            |
|   +-------------+-------------+-------------+--------------+------------+  |
|   |             |             |             |              |            |  |
|   +---------------------------------------------------------------------+  |
|   |             |             |             |              |            |  |
|   +---------------------------------------------------------------------+  |
|   |             |             |             |              |            |  |
|   +---------------------------------------------------------------------+  |
|   |             |             |             |              |            |  |
|   +---------------------------------------------------------------------+  |
|   |             |             |             |              |            |  |
|   +---------------------------------------------------------------------+  |
|   |             |             |             |              |            |  |
|   +-------------+-------------+-------------+--------------+------------+  |
|                                                                            |
+----------------------------------------------------------------------------+
````

Would that by something you had in mind?

**Comment by sputnik27** [comment]
Hi @bodiam,

I do not yet exactly know what it should look like. What I had in mind was the "insert table" action from libreoffice. What I like about that is that you can "see" the shape of the table. I think that using the words "rows" and "columns" is not that intuitive, at least I always have to think which one is which.

![screenshot from 2015-10-25 02 28 15](https://cloud.githubusercontent.com/assets/2292245/10714598/745889ce-7af6-11e5-8ff1-c4f4c6f9585c.png)

I am not sure about the data entry in this dialog. Maybe it is better to keep it as it is currently since AsciiDoc tables are quite easy to edit anyway. I wonder if it could work to have the cursor jump around like for live templates, so that one only has to press `tab` when inserting data?

**Comment by bodiam** [comment]
Hi @sputnik27 ,

Agreed, to be honest, I also often have problems remember which is which :-). The Libreoffice thing is nice, but it looks a bit more complex to make, unless there's a component which does this already?

I'm not sure if jumping around is possible. Could be, but I don't recall having seen that in any other plugin or functionality.

**Comment by bbrenne** [comment]
Hi,

I really would like to have this feature also but preferably in the toolbar, without going into a panel. Does anybody knows if it's possible to have a "menu like" stuff or custom component in the toolbar? (other than just button or checkbox) Does anybody seen complex component in another intelliJ plugin?

**Comment by ahus1** [comment]
The next preview release will contain the following new UI elements thank to @bbrenne! 

![table1](https://user-images.githubusercontent.com/3957921/60714770-fc757400-9f1b-11e9-8b2d-8a8c0f7b18fc.png)
![table2](https://user-images.githubusercontent.com/3957921/60714771-fc757400-9f1b-11e9-9bd6-d569c96dc4f5.png)

**Comment by ahus1** [comment]
0.28.11 is now available as a new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
