### ISSUE TITLE
Cannot export chinese pdf

### ISSUE THREAD

**Issue by gerryhjs** [asciidoctor/asciidoctor-intellij-plugin#952]
This will generate garbled characters

**Comment by gerryhjs** [comment]
![image](https://user-images.githubusercontent.com/45413498/147184959-5f2d9bf8-d5b9-419e-a690-0085b68be7f4.png)

**Comment by gerryhjs** [comment]
When export chinese , chinese characters become garbled.

**Comment by ahus1** [comment]
Hi @gerryhjs - thanks for reaching out. 

The effects you see (empty rectangular boxed) happen when using a font for PDFs where the font doesn't support the characters you want to print. In this case, the default font would support Latin characters, but not Chinese characters.  

In order to create a PDF with Chinese or other non-latin characters, you'll need to provide TTF fonts with the necessary characters. I prepared a [page in the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/pdf-non-latin-languages.html) that should guide you.

If you find the documentation to be incomplete or insufficient for you situation, please provide a minimal example in this issue, for example a ZIP file or a link to a GitHub repo.

**Comment by gerryhjs** [comment]
@ahus1 I see. Thanks.
Its a good idea to add support directly without create zh_CN-theme.yml in the future version.
