### ISSUE TITLE
Update from 0.36.11/0.36.12 not working when IDE's internal mode is enabled

### ISSUE THREAD

**Issue by kriegaex** [asciidoctor/asciidoctor-intellij-plugin#962]
See https://youtrack.jetbrains.com/issue/IDEA-286147

**Comment by ahus1** [comment]
Sorry to hear that the AsciiDoc plugin is not upgrading. Thanks for opening issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/962.

This is plugin related: I assume you have the "internal mode" enabled; this triggers a code path that has a bug when attempting a dynamic update. This doesn't happen if internal mode is disabled.

This is now fixed in 0.36.13. Still, manual intervention is needed to make the local installation upgrade.

For now, I recommend: 
* disable internal mode (at least for this update), restart IDE, and then retry the update - see https://plugins.jetbrains.com/docs/intellij/enabling-internal.html for details on the internal mode
* download the latest version of the AsciiDoc plugin from the plugin's homepage on the marketplace and install it from disk - for the download: https://plugins.jetbrains.com/plugin/7391-asciidoc/versions; on how to install from disk: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation.html#download-install-from-disk

Future updated for 0.36.13 and later will update normally.

**Comment by ahus1** [comment]
I search a bit more and found a registry entry that will disable dynamic plugin updates for all plugins via the key "ide.plugins.allow.unload". This is normally checked, and can be unchecked. To access the registry, go to "Help | Find action...", then search for "Registry", then search for the key.

Still, disabling the internal mode or installing from disk sounds more straight forward. It still might be helpful for those running an EAP version where the internal mode is enabled by default. 

I'll ask upstream if there is another way.

**Comment by kriegaex** [comment]
Temporarily disabling internal mode solved the problem. I was able to update.

**Comment by ahus1** [comment]
Good to hear that this works now and sorry for the troubles. 

The manual-download-from-marketplace is now part of the FAQ as this is the more general approach; disabling the internal mode was specific to the bug that caused it. 

Happy AsciiDoc-coding!
